apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
  labels:
    app: django
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
      version: blue
  template:
    metadata:
      labels:
        app: django
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: derickobeng/messaging-app:2.0
        ports:
        - containerPort: 8000
